// <auto-generated />
using System;
using Business.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Business.Data.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20221027152622_TeacherEntityUpdate")]
    partial class TeacherEntityUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.CourseResponsibles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NumberOfExaminee")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfRegisteredStudents")
                        .HasColumnType("integer");

                    b.Property<Guid?>("QuestionExaminerPartAId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuestionExaminerPartBId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuestionScrutinizerPartAId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuestionScrutinizerPartBId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuestionSetterPartAId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuestionSetterPartBId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("QuestionExaminerPartAId");

                    b.HasIndex("QuestionExaminerPartBId");

                    b.HasIndex("QuestionScrutinizerPartAId");

                    b.HasIndex("QuestionScrutinizerPartBId");

                    b.HasIndex("QuestionSetterPartAId");

                    b.HasIndex("QuestionSetterPartBId");

                    b.HasIndex("ExamId", "CourseId")
                        .IsUnique();

                    b.ToTable("CoursesResponsibles");
                });

            modelBuilder.Entity("Core.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Department", "Session", "Semester")
                        .IsUnique();

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Core.Entities.ExamCommittee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("MemberRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ExamId", "MemberId")
                        .IsUnique();

                    b.ToTable("ExamCommittees");
                });

            modelBuilder.Entity("Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NumberOfExaminee")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfRegisteredStudents")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ExamId", "CourseId")
                        .IsUnique();

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Core.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Institute")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Credit")
                        .HasColumnType("numeric");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Department", "Code")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ProjectTeacher", b =>
                {
                    b.Property<Guid>("ExaminersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectsId")
                        .HasColumnType("uuid");

                    b.HasKey("ExaminersId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("ProjectTeacher");
                });

            modelBuilder.Entity("Core.Entities.CourseResponsibles", b =>
                {
                    b.HasOne("Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Teacher", "QuestionExaminerPartA")
                        .WithMany()
                        .HasForeignKey("QuestionExaminerPartAId");

                    b.HasOne("Core.Entities.Teacher", "QuestionExaminerPartB")
                        .WithMany()
                        .HasForeignKey("QuestionExaminerPartBId");

                    b.HasOne("Core.Entities.Teacher", "QuestionScrutinizerPartA")
                        .WithMany()
                        .HasForeignKey("QuestionScrutinizerPartAId");

                    b.HasOne("Core.Entities.Teacher", "QuestionScrutinizerPartB")
                        .WithMany()
                        .HasForeignKey("QuestionScrutinizerPartBId");

                    b.HasOne("Core.Entities.Teacher", "QuestionSetterPartA")
                        .WithMany()
                        .HasForeignKey("QuestionSetterPartAId");

                    b.HasOne("Core.Entities.Teacher", "QuestionSetterPartB")
                        .WithMany()
                        .HasForeignKey("QuestionSetterPartBId");

                    b.Navigation("Course");

                    b.Navigation("Exam");

                    b.Navigation("QuestionExaminerPartA");

                    b.Navigation("QuestionExaminerPartB");

                    b.Navigation("QuestionScrutinizerPartA");

                    b.Navigation("QuestionScrutinizerPartB");

                    b.Navigation("QuestionSetterPartA");

                    b.Navigation("QuestionSetterPartB");
                });

            modelBuilder.Entity("Core.Entities.ExamCommittee", b =>
                {
                    b.HasOne("Core.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Teacher", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Core.Entities.Project", b =>
                {
                    b.HasOne("Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("ProjectTeacher", b =>
                {
                    b.HasOne("Core.Entities.Teacher", null)
                        .WithMany()
                        .HasForeignKey("ExaminersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
